name: ter

on: workflow_dispatch

jobs:

  build:

    runs-on: windows-latest

    timeout-minutes: 9999

    steps:

    - name: Download Ngrok & NSSM

      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/TheDarkMythos/Ngrok-Exe/master/ngrok.exe -OutFile ngrok.exe
        
        Invoke-WebRequest https://raw.githubusercontent.com/sainskey/ashadualla-ilaha-illallah/main/nssm.exe -OutFile nssm.exe
    - name: Copy NSSM & Ngrok to Windows Directory.

      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Connect your NGROK account

      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Download Important Files.

      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/sainskey/ashadualla-ilaha-illallah/main/NGROK-US.bat -OutFile NGROK-US.bat
        Invoke-WebRequest https://raw.githubusercontent.com/sainskey/ashadualla-ilaha-illallah/main/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/sainskey/ashadualla-ilaha-illallah/main/loop.bat -OutFile loop.bat
        Invoke-WebRequest -Uri https://github.com/actions/runner/releases/download/v2.283.3/actions-runner-win-x64-2.283.3.zip -OutFile actions-runner-win-x64-2.283.3.zip
    - name: Make YML file for NGROK.

      run: start NGROK-US.bat

    - name: Enable RDP Access.

      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel

      run: sc start ngrok
      
    - name: Programmed and developed by hamba allah

      run: echo jangan lupa sholat 5 waktu
      
    - name: ashadualla-ilaha-illallah

      run: cmd /c NGROK-CHECK.bat
      
    - name: ashadualla-ilaha-illallah

      run: cmd /c loop.bat
